---
- name: Detect Homebrew binary path
  ansible.builtin.set_fact:
    brew_bin: "{{ '/opt/homebrew/bin/brew' if ansible_facts['architecture'] == 'arm64' else '/usr/local/bin/brew' }}"

- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: "{{ brew_bin }}"
  register: brew_stat

- name: Install Homebrew
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not brew_stat.stat.exists
  environment:
    NONINTERACTIVE: "1"

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  environment:
    PATH: "{{ brew_bin | dirname }}:{{ ansible_env.PATH }}"
