---
homebrew_taps:
  - koekeishiya/formulae
  - stripe/stripe-cli

homebrew_formulae:
  - cmake
  - cmake-docs
  - lua
  - zsh
  - colima
  - eza
  - fd
  - ffmpeg
  - fzf
  - gdb
  - gh
  - go
  - llvm
  - neovim
  - pipx
  - powerlevel10k
  - pyenv
  - reattach-to-user-namespace
  - ripgrep
  - stow
  - tmux
  - tree
  - vim
  - wget
  - whisper-cpp
  - koekeishiya/formulae/skhd
  - koekeishiya/formulae/yabai
  - stripe/stripe-cli/stripe

homebrew_casks:
  - font-meslo-lg-nerd-font
